#!/usr/bin/env bash

VP9_DASH_PARAMS="-tile-columns 4 -frame-parallel 1"
rm -rf output/*
ffmpeg -f concat -i concat -codec copy output/ALL.MTS
#ffmpeg -i output/ALL.MTS -c:v libvpx-vp9 -filter:v fps=29.97 -s 160x90 -b:v 100k -keyint_min 150 -g 150 ${VP9_DASH_PARAMS} -an -f webm -dash 1 output/video_160x90_250k.webm
#ffmpeg -i output/ALL.MTS -c:v libvpx-vp9 -filter:v fps=29.97 -s 320x180 -b:v 250k -keyint_min 150 -g 150 ${VP9_DASH_PARAMS} -an -f webm -dash 1 output/video_320x180_500k.webm
ffmpeg -i output/ALL.MTS -c:v libvpx-vp9 -filter:v fps=29.97 -s 640x360 -b:v 50k -minrate 50k -maxrate 50k -keyint_min 150 -g 150 ${VP9_DASH_PARAMS} -an -f webm -dash 1 output/video_640x360_300M.webm
exit 0
ffmpeg -i output/ALL.MTS -c:v libvpx-vp9 -filter:v fps=29.97 -s 640x360 -b:v 1000k -keyint_min 150 -g 150 ${VP9_DASH_PARAMS} -an -f webm -dash 1 output/video_640x360_1000k.webm
ffmpeg -i output/ALL.MTS -c:v libvpx-vp9 -filter:v fps=29.97 -s 1280x720 -b:v 1500k -keyint_min 150 -g 150 ${VP9_DASH_PARAMS} -an -f webm -dash 1 output/video_1280x720_500k.webm
ffmpeg -i output/ALL.MTS -c:a libvorbis -b:a 32k -vn -f webm -dash 1 output/audio_32k.webm
ffmpeg -i output/ALL.MTS -c:a libvorbis -b:a 64k -vn -f webm -dash 1 output/audio_64k.webm
ffmpeg -i output/ALL.MTS -c:a libvorbis -b:a 128k -vn -f webm -dash 1 output/audio_128k.webm
ffmpeg \
 -f webm_dash_manifest -i output/video_160x90_250k.webm \
 -f webm_dash_manifest -i output/video_320x180_500k.webm \
 -f webm_dash_manifest -i output/video_640x360_750k.webm \
 -f webm_dash_manifest -i output/video_640x360_1000k.webm \
 -f webm_dash_manifest -i output/video_1280x720_500k.webm \
 -f webm_dash_manifest -i output/audio_32k.webm \
 -f webm_dash_manifest -i output/audio_64k.webm \
 -f webm_dash_manifest -i output/audio_128k.webm \
 -c copy -map 0 -map 1 -map 2 -map 3 -map 4 -map 5 \
 -f webm_dash_manifest -adaptation_sets "id=0,streams=0,1,2,3,4 id=1,streams=5,6,7" \
 output/manifest.mpd

# vim: ft=sh:tw=0
