var _ = require('underscore'),
    path = require('path'),
    common = require('./common.js'),
    fs = require('fs'),
    jsonfile = require('jsonfile'),
    uuid = require('node-uuid');

module.exports = function(config) {
  return function(files, metalsmith, done) {
    lessonDirectories = _.map(common.lessonfiles(files), function (file, filename) {
      return path.dirname(filename);
    });
    _.each(files, function (file, filename) {
      containingLessons = _.filter(lessonDirectories, function (prefix) {
       return path.dirname(filename).startsWith(prefix);
      });
      if (containingLessons.length > 1) {
        done(new Error(filename + " is in two lesson subdirectories."));
      } else if (containingLessons.length == 1 && path.basename(filename) !== 'lesson.adoc') {
        if (file.lesson) {
          done(new Error(filename + " already contains a lesson attribute and should not."));
        }
        file.lesson = containingLessons[0];
      }
    });
    newLessons = [];
    _.each(lessonDirectories, function (lessonDirectory) {
      lessonIDPath = path.join(lessonDirectory, '.uuid.json');
      if (lessonIDPath in files) {
        files[lessonIDPath].lesson.uuid = JSON.parse(files[lessonIDPath].contents).uuid;
        delete(files[lessonIDPath]);
      } else {
        jsonfile.writeFileSync(path.join(metalsmith.source(), lessonIDPath), {
          'uuid': uuid.v4(),
          'note': "This file is autogenerated. " + 
                  "It uniquely identifies this lesson. " + 
                  "Do not change or delete it. " + 
                  "If you move this lesson, move this file along with it. " +
                  "Please see src/content/README.adoc for more details."
        });
        newLessons.push(lessonDirectory);
      }
    });
    if (newLessons.length > 0) {
      console.log("Identified and uniquely labeled " + newLessons.length + " new lesson(s).");
      console.log("New .uuid.json files have been created. " +
          "They should be kept with their lesson.adoc file.");
      console.log("Please see src/content/README.adoc for more details.");
    }
    done();
  }
};

// vim: ts=2:sw=2:et
