---
title: "CSE 199 Fall 2016"
spelling_exceptions:
  - Geoff
  - GWA
description: >
  Syllabus for CSE 199: How the Internet Works
priority: 0.8
changefreq: monthly
layout: course/syllabus.hbt
flowtext: true
doSections: true
---
:linkattrs:

== Overview

The internet is changing every aspect of our lives, including how we
communicate, learn, navigate, organize, work, play, and love.
//
The internet also represents a crowning achievement of computing: a single
system uniting hardware and software, theory and implementation, standards
and innovation, engineering and science, protests that topple governments and
stupid cat videos.
//
This course provides an overview of how the internet works by describing
everything required to answer a single search query.
//
Along with its technologies, we will delve into the internet’s past and
future, policy challenges, and societal implications.
//
The course is targeted at a general audience, but because the internet
reflects contributions from many areas of computer science and computer
engineering, it also provides a good overview for potential majors.
//
Familiarity with the web and access to a personal computer are assumed, but
no technical background is required.

[[approach]]
== Approach

CSE 199 is being taught a bit differently than some other courses that you
might take at college.
//
Rather than a series of lectures with homework outside of class, we're going
to assign lectures (in the form of short videos) _outside_ of class and have
you do interesting activities _inside_ class.
//
This is sometimes know as the
https://en.wikipedia.org/wiki/Flipped_classroom[flipped classroom] model.
//
So rather than referring to our large meetings as lectures, we're calling
them _activity sections_.
//
You'll have two one-hour activity sections per week plus one one-hour
recitation in a smaller group of around 25 to 30 students.

Because how we are teaching you is a bit different, your responsibilities as
as student are a bit different.
//
Here's how a typical week would work from your perspective:

. *Before class on Monday and Wednesday*: watch the assigned videos online.
//
Monday's activity will depend on knowledge obtained from these videos.
//
We are recording around 60 to 90 minutes of video content per week in the
form of 12 to 18 5 minute videos.
//
So you should expected to watch around 30 to 45 minutes of video content
before each activity section.
//
We consider that to be reasonable, and we will try to keep the videos a lot
more interesting than your average textbook.
//
However, we would advise budgeting at least 60 to 90 minutes before each
class to complete the video assignments--in case you need to watch one more
than once or return to videos to review.
//
. *In class on Monday and Wednesday*: complete an interesting activity in
small groups of around four students.
//
Each activity section has around 6 undergraduate teaching assistants and an
instructor that will be on hand to help out during class.
//
. *In recitation on Thursday or Friday*: discuss the week's material in a
smaller group.
//
Recitations are a great chance to ask questions about the video content and
engage in discussions surrounding the material.

Note that <<grades,your grade>> in this course is largely driven by
participation--watching the videos online and coming to class and completing
the in-class activities.
//
We have a few bits of homework for you to complete outside of class, but
we've mostly moved the homework _inside_ of the classroom.
//
That's one of the advantages of the flipped classroom model.

[[calendar]]
== Calendar

We suggest that you add our http://goo.gl/5D6g2E[global CSE 199 calendar] to
your calendaring program.
//
If you are not using a calendaring program, we suggest that you begin using a
calendaring program.

Note that the calendar below only has things applicable to all CSE 199
students.
//
These include weekly activities, staff office hours, open shooting sessions,
movie nights, and <<dates,important dates>>.
//
This calendar does _not_ include activity section meeting or recitation
meeting times and locations.

++++
<div class="video-container">
<iframe
src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showCalendars=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=buffalo.edu_f47q0orjhk0a5vjrngcjs0jrt8%40group.calendar.google.com&amp;color=%23853104&amp;ctz=America%2FNew_York"
style="border-width:0" width="800" height="600" frameborder="0"
scrolling="no"></iframe>
</div>
++++

[[dates]]
=== Other Important Dates

Also on the <<calendar,calendar>>.
//
The registrar's office has their own semi-useful calendar
link:++http://calendar.registrar.buffalo.edu/calendar/?ai1ec=action~month++[here].

* *Last day to drop or add courses*: Tuesday 9/6/2016
* *Midterm grade deadline*: Friday 10/4/2016
* *Last day to resign*: Friday 11/11/2016
* *Last day of class*: Friday 12/9/2016
* *Final grade deadline*: Monday 12/26/2016

== Information

=== Course Staff

link:https://blue.cse.buffalo.edu[Geoffrey Challen] is providing most of the
content for the class in the form of short videos.
//
But you will notice contributions from others--including other course staff,
other UB CSE faculty members, and hopefully eventually alumni and external
experts footnote:[You will also have a chance to contribute your own videos
as a course assignment.].
//
The four fantastic faculty leading activity sections are
http://www.cse.buffalo.edu/~hartloff/index.html[Jesse Hartloff],
http://www.cse.buffalo.edu/people/?u=mhertz[Matthew Hertz],
http://www.cse.buffalo.edu/people/?u=ahughes6[Andrew Hughes], and
http://www.cse.buffalo.edu/people/?u=jwinikus[Jennifer Winikus].

We have a great group of undergraduate and graduate teaching assistants to
help you learn about the internet.
//
https://blue.cse.buffalo.edu/people/gjbunyea/[Greg Bunyea] is serving as the
head undergraduate teaching assistant.
//
https://blue.cse.buffalo.edu/people/carlnues[Carl Nuessle] is serving as the
head (and only) graduate teaching assistant.
//
The 24 other teaching assistants are Aishani Bhalla, Mohit Bhatia, Isabelle
Caneda, Wesley Csendom, Junjie Chen, Michael Drewitt, David Dobmeier, Lakshmi
Ethiraj, Richard Hanulewicz, Liam Gensel, Harshita Girase, Patrick Jones,
Heeba Kariappe, Valencia Kaplinsky, Lawreen Latif, Angus Lam, Ian Ngumi,
Brijesh Rakholia, Rachel Roberts, Parth Shah, Kyle Schoener, Dan Starner,
Evan Walley, and Grant Wrazen.
//
Phew!
//
That's quite a group.
//
Instructors and teaching assistants are broken down by activity section
<<sections,below>>.

=== Times and Locations

Times and locations for <<sections,activity sections>> and
<<recitations,recitations>> are listed below.
//
You can also find this information on the HUB.

In addition to activity sections and recitations we are planning a number of
other optional--but fun--activities.
//
First, we have several movie nights planned for the semester where we will
watch some great internet-related films footnote:[Clearly Werner Herzog timed
the release of http://www.loandbeholdfilm.com/[Lo and Behold] to coincide
with our class...].
//
Second, we will hold open shooting sessions each week on Wednesday starting
at 10AM.
//
We're still shooting footage for the later weeks in the class, so if you'd
like to be part of the studio audience you are more than welcome--although I
can't spring for any fancy prizes.
//
Details about both of these events will be on the <<calendar,course
calendar>>.
//
The course calendar will also list office hours for all CSE 199 instructors.

=== Textbook

There is no required textbook for this course.

=== Exams

We will not give any exams.

=== Prerequisites

There are no prerequisites.

== Description

The course is broken into weekly topic units as described below.
//
Note that topics covered in each week will be discussed at a very high level
and not in anywhere close to as much detail as would be included by more
advanced courses for CSE majors footnote:[Like
http://www.cse.buffalo.edu/faculty/dimitrio/courses/cse4589_s14/[CSE 489],
taught at least sometimes by the all-knowning--yet
shy&mdash;http://www.cse.buffalo.edu/faculty/dimitrio/[Dimitrios
Koutsonikolas].].
//
Using the
https://en.wikipedia.org/wiki/Transmission_Control_Protocol[transmission
control protocol (TCP)] as an example:

* A _detailed technical description_ of
TCP in an advanced CSE course would include description of the various parts
of the TCP header; the handshakes that establish and terminate connections;
acknowledgements, selective acknowledgements, and retransmissions; maximum
segment sizes and IP fragmentation; and dynamics of flow control including
congestion window sizing.
//
* In contrast, in CSE 199 we will explain that the protocol is used to create
a connection between two internet hosts by establishing reliable ordered
delivery of data packets not provided by the internet protocol (IP) alone,
while also explaining that TCP helps share network resources between active
hosts.

Thus higher-level internet design goals and concepts can be discussed without
going into any of the technical details described above footnote:[Which are
also, let's face it, somewhat dull.].

=== Outline

We reserve the right to adjust this schedule as needed.
//
That said, here's what we are trying to accomplish on a week-by-week basis:

. *The Internet Era*: what the internet is, why it is worth studying,
networking terminology, difference between the internet and the World Wide
Web, internet ownership, internet standardization, finding out more about the
internet, "Eternal September".
//
. *Connectivity*: cables, connected at work and at home, the last mile
problem, the core internet, packets, circuit v. packet switching.
//
. *Protocols*: what is a protocol, clients and servers, the internet protocol
(IP), IP addresses, the end-to-end principle, protocol stacks, encapsulation,
other internet protocols, peer-to-peer systems.
//
. *Routing*: routers and end hosts, autonomous systems, the border gateway
protocol, meet-me rooms, IP address structure, 512K day, traceroute, routing
stability, public v. private addresses, onion routing.
//
. *Transport*: the TCP protocol, TCP connections, ports, well-known port
numbers, NAT, problems with TCP, QUIC, TCP influence on overall network
design, buffer bloat, the UDP protocol and unreliable connections, multipath
TCP.
//
. *Naming*:  the domain name service (DNS) and DNS protocol, machine- and
human-readable names, name translation, top-level domains, IPv4 and routing,
name assignment, IPv4 address exhaustion, IPv6 and adoption problems.
//
. *Web Queries, Documents and Markup*: the HTTP protocol, HTML and CSS,
separation of content and presentation, links, the DOM data structure,
previous attempts like Gopher, the internet before the WWW, static and
dynamic web pages, server-side rendering, forms, HTTP GET key-value pairs,
GET v. POST.
//
. *Crawling, Indexing and Ranking the Web*: web crawling and processing, the
internet archive, data center computing, distributed indexes, mapreduce, data
center networking, software-defined networking, the pagerank algorithm,
improving ranking using context, history, click tracking, website reputation.
//
. *Security and Authority*: certificates and certificate authorities, public
key encryption, symmetric key encryption, trusted hardware modules, security
protocol vulnerabilities.
//
. *Identity and Privacy*: cookies, server side tracking, IP addresses v.
identities, anonymity online, online v. human identities.
//
. *The Interactive Web*: Javascript, web applications, asynchronous web
requests, modifying the DOM.
//
. *The Mobile and Pervasive Web*: internet architecture problems created by
mobility, limitations of mobile devices, mobile web performance problems and
solutions, MPTCP and multihoming, the IoT, pervasive computing, energy and
physical constraints on tiny devices, IPv6 and network growth, the physical
web.
//
. *Your Brain on the Internet*: attention, concentration, distraction, deadly
accidents, search v. knowledge, controlling our internet usage.
//
. *Internet Content and Economics*: early proposals for early payments via
link counting, Bitcoin as an online currency, DRM and other efforts to
prevent digital copying, ongoing efforts to find and block online content.
//
. *Lost and Future Visions of the Internet*: Berners-Lee’s original vision
for collaborative content and arguments with Netscape, early internet
communities like the WELL, modern internet communities like 4chan and the
drug site, Lessig’s vision of an internet commons, Proposals for future
improvements to the internet architecture, and will they ever be realized?

=== Objectives

The table below describes how this course meets the learning objectives of
the University at Buffalo
https://www.buffalo.edu/ubcurriculum/seminar.html[UB Seminar program]:

[cols=3,options='header',role='small']
|===

| Outcome
| Activities
| Assessment

| Think critically using multiple modes of inquiry
//
| Online quizzes, group projects, video assignment, final assignment
//
| All assignments

| Analyze disciplinary content
//
| Online quizzes, group projects, video assignment, final assignment
//
| All assignments

| Understand and apply methods of close reading, note-taking, analysis, and
synthesis
//
| Online quizzes, group projects, video assignment, final paper
//
| All assignments, but particularly the video assignments

| Recognize and debate ethical issues and academic integrity footnote:[FWIW,
there is no "debate" about academic integrity...]
//
| Group projects
//
| Multiple weekly projects will touch on ethical issues; academic integrity
will be discussed as a downside of web search.

| Demonstrate proficiency in oral discourse and written communication
//
| Video assignments
//
| Preparation of video assignments

| Develop essential research and study skills such as time management
//
| Online quizzes and module scheduling
// 
| Online quizzes ensure students are proceeding at the appropriate pace.

| Utilize eportfolio footnote:[Why?]
//
| Video assignments
//
| Video lessons will be deposited in eportfolio as well as on YouTube.

| Understand the academic expectations pertaining to studentship at the
University at Buffalo and to higher learning at a research university
//
| Group assignments
//
| Inherent to the structure of the course, preparation for class and for
group assignments.

| Develop a broader perspective for help in making life choices in their
college careers and beyond
//
| Group assignments, final paper
//
| Multiple weekly assignments will touch on societal and ethical issues and
discuss how the internet is changing the broader world.

|===

== Grading

Grading is largely driven by participation:

* *30% video participation*: watching the online videos.
//
* *30% activity participation*: coming to class and completing activities
with your group.
//
* *30% video contributions*: recording and uploading three short videos (10%
each) with a group drawn from your activity section.
//
* *10% internet participation*: generating or curating online content.

We discuss each of the grading components in more detail below.

=== Video Participation

Watching the videos _before_ coming to class is critical for <<approach,our
approach>> to work.
//
We will monitor and quantify your progress through the video series in a
variety of ways.

=== Activity Participation

Equally important to success in this course is coming to class and
participating in the activities.
//
We will assign you to a new random group for each activity section, and one
group member will be responsible for submitting the group's work and
recording what group members were present.
//
Missing one or two classes during the semester is fine--that happens to
anyone.
//
Missing class repeatedly will make it hard to pass this class.

=== Video Contributions

One of the best ways to learn new material is to explain it to others.
//
We're providing you a way to do that--but to hundreds or thousands of
students in coming years.
//
During the semester you will need to record three short videos for inclusion
in the link:/[`internet-class.org`] video library.
//
Some will be alternative explanations for existing concepts, but in other
cases we will ask you to describe and explain a topic that is related to
the material but not currently covered.
//
More details on these assignments will follow shortly.

=== Internet Participation

As a final assignment we will ask you to participate in the internet.
//
That can take a variety of forms: creating a personal website or blog,
maintaining a https://www.wikipedia.org/[Wikipedia] page, contributing to a
open source software project perhaps on https://www.github.com[GitHub], etc.
//
We are open to many different ideas here, but just to note: normal social
networking activities _will not_ earn you credit for this activity.
//
You'll discuss this assignment in more detail with your activity section
leader and course staff later in the semester.

=== Grade Mapping

Your score in the course will be converted to a letter grade as follows:

[cols=3,options='header']
|===

| Letter Grade
| Max
| Min

| A
| 100
| 94

| A-
| 93
| 90

| B+
| 89
| 87

| B
| 86
| 84

| B-
| 83
| 80

| C+
| 79
| 77

| C
| 76
| 74

| C-
| 73
| 70

| D
| 69
| 60

| F
| 59
| 0

|===

=== Incomplete Grades

Please refer to the
http://undergrad-catalog.buffalo.edu/policies/grading/explanation.shtml#incomplete[undergraduate]
incomplete policy. Of particular importance is this language:

[quote]
Students may only be given an *I* grade if they have a passing average in
coursework that has been completed and have well-defined parameters to
complete the course requirements that could result in a grade better than the
default grade. _An *I* grade may not be assigned to a student who
  did not attend the course._

=== Academic Integrity

Please review the http://www.cse.buffalo.edu/shared/policies/academic.php[CSE
Department academic integrity policy] and the UB
http://undergrad-catalog.buffalo.edu/policies/course/integrity.shtml[undergraduate]
academic integrity policy to familiarize yourself with the relevant academic
integrity policies and procedures.
//
*Students that submit plagiarized work will receive a grade of F for the
course.*

=== Disabilities

Please register and coordinate with the Office of Disability Services. Let
the course staff know when accommodations need to be made. We are committed
to helping you learn.

=== Online Resources

This website is the source for all information about the class: the syllabus
(which you are reading) and the video series.

=== Mailing List

All enrolled students will be added to a mailing list which we will use for
course communication.
//
*You are responsible for email messages sent to this list, and to your
`@buffalo.edu` email address.*
//
If you are not enrolled and would like to be added to the list, you can sign
up https://www.internet-class.org/mailman/listinfo/199[here].

== Getting Help

Here's how to--and how not to--get help.

=== Great Ways to Get Help

* *Use the the forum.*
//
We will set up an online forum for you to discuss the videos and activities.
//
This is a great resource because it allows you to get help from anyone at any
time--not just during class or recitation.
//
Please use and contribute to this valuable shared resource.

* *Come to office hours.* We don't hold them for our health and
instructors get bored when there isn't anyone to help!
//
So please don't hesitate to come by, even just to say hi.

=== Bad Ways to Get Help

* *Emailing any staff member using their `@buffalo.edu` email address.*
//
I instruct the staff to ignore these emails.
//
Use the forum or talk to them during class.


[[sections]]
== Sections

Information specific to each activity section follows.
//
https://blue.cse.buffalo.edu/people/gwa/[Geoffrey Challen] may drop in on any
of these sections at any time.
//
And of course https://blue.cse.buffalo.edu/people/carlnues/[Carl Nuessle] has
been known to show up anywhere at any time as well--so be ready.

=== 199A

. *Instructor*: http://www.cse.buffalo.edu/~hartloff/index.html[Jesse
Hartloff]
//
. *Teaching Assistants*: Junjie Chen, Richard Hanulewicz, Valencia Kaplinsky,
Rachel Roberts, Kyle Schoener, and Grant Wrazen
//
. *Dates and Times*: MW at 4PM in Hochstetter 114

=== 199B

. *Instructor*: http://www.cse.buffalo.edu/people/?u=mhertz[Matthew Hertz]
//
. *Teaching Assistants*: David Dobmeier, Lakshmi Ethiraj, Harshita Girase,
Patrick Jones, Angus Lam, Brijesh Rakholia, and Evan Walley
//
. *Dates and Times*: MW at 4PM in Knox 110

=== 199C

. *Instructor*: http://www.cse.buffalo.edu/people/?u=jwinikus[Jennifer
Winikus]
//
. *Teaching Assistants*: Liam Gensel, Heeba Kariapper, Lawreen Latif, Ian
Ngumi, Parth Shah, and Dan Starner
//
. *Dates and Times*: MW at 4PM in NSC 210

=== 199C

. *Instructor*: http://www.cse.buffalo.edu/people/?u=ahughes6[Andrew Hughes]
footnote:[Whose site is in serious need of an overhaul.]
//
. *Teaching Assistants*: Aishani Bhalla, Mohit Bhatia, Greg Bunyea, Isabelle
Caneda, Wesley Csendom, Michael Drewitt, and occasionally Geoffrey Challen.
//
. *Dates and Times*: MW at 9AM in Alumni 97

// vim: ts=2:et:ft=asciidoc
