---
title: "CSE 199 Syllabus"
spelling_exceptions:
  - DIY
  - eportfolio
  - Capen
  - Silverman
  - 4chan
  - S'More
  - renormalized
  - Werner Herzog
  - Codecademy
  - CodeCombat
  - Faux
  - Instagram
  - LinkedIn
description: >
  Syllabus for CSE 199: How the Internet Works
priority: 0.8
changefreq: monthly
layout: syllabus.hbt
flowtext: true
doSections: true
---
:linkattrs:

== Overview

The internet is changing every aspect of our lives, including how we
communicate, learn, navigate, organize, work, play, and love.
//
The internet also represents a crowning achievement of computing: a single
system uniting hardware and software, theory and implementation, standards
and innovation, engineering and science,
https://en.wikipedia.org/wiki/Social_media_and_the_Arab_Spring[protests that
topple governments]
//
and
//
http://tubularinsights.com/2-million-cat-videos-youtube/[adorable cat
videos].

This course provides an overview of how the internet works by describing
everything required to answer a single search query.
//
Along with its technologies, we will delve into the internet’s past and
future, policy challenges, and societal implications.
//
The course is targeted at a general audience.
//
But because the internet reflects contributions from many areas of computer
science and computer engineering, it also provides a good overview for
potential majors.
//
Familiarity with the web and access to a personal computer are assumed, but
no technical background is required.

== Announcements

We're trying announcements through video this semester. Here's the playlist:

++++
<div class="video-container">
<div class="lazy-iframe"
data-src="https://www.youtube.com/embed/videoseries?list=PLk97mPCd8nvb3LuRd9PKgSE9wgeoUjj08&amp;showinfo=1"></div>
</div>
++++

[[forum]]
== Forum

We've set up a Discourse forum for students to use
https://discourse.internet-class.org/[here].
//
The forum is the place to go to peruse announcements, find out more about the
course, and get help with any technical issues you might be having.
//
Please ask questions on the forum before approaching the course staff--this
will help you get a reply quicker!

[[approach]]
== Approach

CSE 199 is being taught a bit differently than some other courses that you
might take at college.
//
Rather than a series of lectures with homework outside of class, we're going
to assign lectures (in the form of short videos) _outside_ of class and have
you do interesting activities _inside_ class.
//
This is sometimes know as a
https://en.wikipedia.org/wiki/Flipped_classroom[flipped classroom].
//
So rather than referring to our large meetings as lectures, we're calling
them _activity sections_.
//
You'll have two one-hour activity sections per week plus one one-hour
recitation in a smaller group of 25&ndash;30 students.

Because how we are teaching you is a bit different, your responsibilities as
as student are a bit different.
//
Here's how a typical week would work from your perspective:

. *Before your activity section on Monday and Wednesday*: watch the assigned
videos online.
//
Activities will depend on knowledge obtained from these videos.
//
We are recording 60&ndash;90 minutes of video content per week in the form of
5 minute videos.
//
So you should expect to watch around 30&ndash;45 minutes of video content
before each activity section.
//
We consider that to be reasonable, and we will try to keep the videos a lot
more interesting than your average textbook.
//
However, we would advise budgeting at least 60&ndash;90 minutes before each
class to complete the video assignments.
//
This leaves time in case you need to watch one more than once or return to
videos to review.
//
. *In your Monday and Wednesday activity section*: complete an interesting
activity in small groups of three or four students.
//
Each activity section has around multiple undergraduate teaching
assistants--about one per four groups--and at least one instructor that will
be on hand to help out during class.
//
You will need to check out of each activity section to receive credit.
//
This involves approaching a teaching assistant and showing them that you have
completed the activity.
//
Rubrics for each activity will vary, but it is more important to use that you
show up and do your best than that you complete every part of the activity.
//
Some activities you may find easy; others will be more challenging.
//
. *In recitation on Thursday or Friday*: discuss the week's material in a
smaller group.
//
Recitations are a great chance to ask questions about the video content and
engage in discussions surrounding the material.

Note that <<grades,your grade>> in this course is largely driven by
participation--watching the videos online and coming to class and completing
the in-class activities.
//
We have a few bits of homework for you to complete outside of class, but
we've mostly moved the homework _inside_ of the classroom.
//
That's one of the advantages of the flipped classroom model.

[[calendar]]
== Calendar

We suggest that you add our http://goo.gl/5D6g2E[global CSE 199 calendar] and
the appropriate calendar for your <<sections,activity section>> to your
calendaring program.
//
If you are not using a calendaring program, we suggest that you begin using a
calendaring program.

Note that the calendar below only has things applicable to all CSE 199
students.
//
These include weekly activities, staff office hours, open shooting sessions,
movie nights, and <<dates,important dates>>.
//
This calendar does _not_ include activity section meeting or recitation
meeting times and locations.
//
Activity sections are on section-specific calendars shown <<sections,below>>.
//
Please add recitations to your own personal calendar as needed.

++++
<div class="video-container">
  <div class="show-on-small hide-on-med-and-up">
    <div class="lazy-iframe" data-src="https://calendar.google.com/calendar/embed?mode=AGENDA&amp;showTitle=0&amp;showCalendars=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=buffalo.edu_f47q0orjhk0a5vjrngcjs0jrt8%40group.calendar.google.com&amp;color=%23853104&amp;ctz=America%2FNew_York"></div>
  </div>
  <div class="hide-on-small-only show-on-med-and-up">
    <div class="lazy-iframe" data-src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showCalendars=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=buffalo.edu_f47q0orjhk0a5vjrngcjs0jrt8%40group.calendar.google.com&amp;color=%23853104&amp;ctz=America%2FNew_York"></div>
  </div>
</div>
++++

[[dates]]
=== Other Important Dates

Also on the <<calendar,calendar>>.
//
The registrar's office has their own semi-useful calendar
link:++http://calendar.registrar.buffalo.edu/calendar/?ai1ec=action~month++[here].

* *Last day to drop or add courses*: Tuesday 9/6/2016
* *Midterm grade deadline*: Friday 11/4/2016
* *Last day to resign*: Friday 11/11/2016
* *Last day of class*: Friday 12/9/2016
* *Final grade deadline*: Monday 12/26/2016

== Information

=== Course Staff

link:https://blue.cse.buffalo.edu[Geoffrey Challen] is providing most of the
content for the class in the form of short videos.
//
But you will notice contributions from others--including other course staff,
other UB CSE faculty members, and hopefully eventually alumni and external
experts footnote:[You will also have a chance to contribute your own videos
as a course assignment.].
//
The four fantastic faculty leading activity sections are
http://www.cse.buffalo.edu/~hartloff/index.html[Jesse Hartloff],
http://www.cse.buffalo.edu/people/?u=mhertz[Matthew Hertz],
http://www.cse.buffalo.edu/people/?u=ahughes6[Andrew Hughes], and
http://www.cse.buffalo.edu/people/?u=jwinikus[Jennifer Winikus].

We have a great group of undergraduate and graduate teaching assistants to
help you learn about the internet.
//
https://blue.cse.buffalo.edu/people/gjbunyea/[Greg Bunyea] is serving as the
head undergraduate teaching assistant.
//
https://blue.cse.buffalo.edu/people/carlnues[Carl Nuessle] is serving as the
head (and only) graduate teaching assistant.
//
The 24 other teaching assistants are Aishani Bhalla, Mohit Bhatia, Isabelle
Caneda, Wesley Csendom, Junjie Chen, Michael Drewitt, David Dobmeier, Lakshmi
Ethiraj, Richard Hanulewicz, Liam Gensel, Harshita Girase, Patrick Jones,
Heeba Kariapper, Valencia Kaplinsky, Lawreen Latif, Angus Lam, Ian Ngumi,
Brijesh Rakholia, Rachel Roberts, Parth Shah, Kyle Schoener, Dan Starner,
Evan Walley, and Grant Wrazen.
//
Phew!
//
That's quite a group.
//
Instructors and teaching assistants are broken down by activity section
<<sections,below>>.

=== Times and Locations

Times and locations for <<sections,activity sections>> and
<<recitations,recitations>> are listed below.
//
You can also find this information on the HUB.

In addition to activity sections and recitations we are planning a number of
other optional--but fun--activities.
//
First, we have several movie nights planned for the semester where we will
watch some great internet-related films footnote:[Clearly Werner Herzog timed
the release of http://www.loandbeholdfilm.com/[Lo and Behold] to coincide
with our class...].
//
Second, we will hold open shooting sessions each week on Wednesday starting
at 10AM.
//
We're still shooting footage for the later weeks in the class, so if you'd
like to be part of the studio audience you are more than welcome--although I
can't spring for any fancy prizes.
//
Details about both of these events will be on the <<calendar,course
calendar>>.
//
The course calendar will also list office hours for all CSE 199 instructors.

=== Textbook

There is no required textbook for this course.

=== Exams

We will not give any exams.

=== Prerequisites

There are no prerequisites.

== Description

The course is broken into weekly topic units as described below.
//
Note that topics covered in each week will be discussed at a very high level
and not in anywhere close to as much detail as would be included by more
advanced courses for CSE majors footnote:[Like
http://www.cse.buffalo.edu/faculty/dimitrio/courses/cse4589_s14/[CSE 489],
taught at least sometimes by the all-knowing--yet
shy&mdash;http://www.cse.buffalo.edu/faculty/dimitrio/[Dimitrios
Koutsonikolas].].
//
Using the
https://en.wikipedia.org/wiki/Transmission_Control_Protocol[transmission
control protocol (TCP)] as an example:

* A _detailed technical description_ of
TCP in an advanced CSE course would include description of the various parts
of the TCP header; the handshakes that establish and terminate connections;
acknowledgments, selective acknowledgments, and retransmissions; maximum
segment sizes and IP fragmentation; and dynamics of flow control including
congestion window sizing.
//
* In contrast, in CSE 199 we will explain that the protocol is used to create
a connection between two internet hosts by establishing reliable ordered
delivery of data packets not provided by the internet protocol (IP) alone,
while also explaining that TCP helps share network resources between active
hosts.

Thus higher-level internet design goals and concepts can be discussed without
going into any of the technical details described above footnote:[Which are
also, let's face it, somewhat dull.].

=== Outline

We reserve the right to adjust this schedule as needed.
//
That said, here's what we are trying to accomplish on a week-by-week basis:

. *The Internet Era*: what the internet is, why it is worth studying,
networking terminology, difference between the internet and the World Wide
Web, internet ownership, internet standardization, finding out more about the
internet, "Eternal September".
** *Activities*: https://goo.gl/84pxLp[Internet Avoidance (2016-08-31)]
** *Videos*:
https://www.youtube.com/playlist?list=PLk97mPCd8nvZZdQHM91vx-eHTJJOmQOEK[Internet Era playlist]
//
. *Connectivity*: [[connectivity]] cables, connected at work and at home, the
last mile problem, the core internet, packets, circuit v. packet switching.
** *Activities*: https://goo.gl/XIgNXO[Connection Detection (2016-09-07)]
** *Videos*:
https://www.youtube.com/playlist?list=PLk97mPCd8nvYJqvvQkhHdMZ8_vgde_rVH[Connectivity playlist]
//
. *Protocols*: [[protocols]] what is a protocol, clients and servers, the
internet protocol (IP), IP addresses, the end-to-end principle, protocol
stacks, encapsulation, other internet protocols, peer-to-peer systems.
** *Activities*: https://goo.gl/7KKbhJ[DIY RFC (2016-09-12)],
https://goo.gl/NJmcUG[Human-Computer Interaction (2016-09-14)]
** *Videos*:
https://www.youtube.com/playlist?list=PLk97mPCd8nvayBmPKnaIdgdYIKpuhpJoe[Protocols playlist]
//
. *Routing*: [[routing]] routers and end hosts, autonomous systems, the border gateway
protocol, meet-me rooms, IP address structure, 512K day, traceroute, routing
stability, public v. private addresses, onion routing.
** *Activities*: https://goo.gl/Wf1cvD[S'More Routing (2016-09-19)],
https://goo.gl/7gddaN[Tracking with `traceroute` (2016-09-21)]
** *Videos*:
https://www.youtube.com/playlist?list=PLk97mPCd8nvZJs7DyfPgiUDovil2K7axM[Routing playlist]
//
. *Transport*: [[transport]] the TCP protocol, TCP connections, ports, well-known port
numbers, NAT, problems with TCP, QUIC, TCP influence on overall network
design, buffer bloat, the UDP protocol and unreliable connections, multipath
TCP.
** *Activities*: https://goo.gl/YZ68jb[Video Review Session (2016-09-26)],
https://goo.gl/QWFGSY[Great White `wireshark` (2016-09-28)]
** *Videos*:
https://www.youtube.com/playlist?list=PLk97mPCd8nvZdbYzA6om36xT-D-Tuew3F[Transport playlist]
//
. *Naming*: [[naming]] the domain name service (DNS) and DNS protocol, machine- and
human-readable names, name translation, top-level domains, IPv4 and routing,
name assignment, IPv4 address exhaustion, IPv6 and adoption problems.
** *Activities*: https://goo.gl/sG4YGV[All Kinds of Names (2016-10-03)],
https://goo.gl/QJ79Hv[Name Tools (2016-10-05)]
** *Videos*:
https://www.youtube.com/playlist?list=PLk97mPCd8nvZgvqcZWzGHmqlcwr_1a3QK[Naming playlist]
//
. *Web*: [[queries]] the HTTP protocol, HTML and CSS,
separation of content and presentation, links, the DOM data structure,
previous attempts like Gopher, the internet before the WWW, static and dynamic
web pages, server-side rendering, forms, HTTP GET key-value pairs, GET v.
POST.
** *Activities*: https://goo.gl/51cvgP[`git` a Personal Website I
(2016-10-10)] (https://youtu.be/8x6InF3s8eM[Video Walkthrough]),
https://goo.gl/FHxeqf[`git` a Personal Website II (2016-10-12)]
(https://youtu.be/8QaI18MyxGs[Video Walkthrough])
** *Videos*:
https://www.youtube.com/playlist?list=PLk97mPCd8nvaAtrsVGbdeNtwf-moYNq-E[Web playlist]
//
. *Search*: [[search]] web crawling and processing, the
internet archive, data center computing, distributed indexes, MapReduce, data
center networking, software-defined networking, the PageRank algorithm,
improving ranking using context, history, click tracking, website reputation.
** *Activities*: https://goo.gl/896Lc9[Personal Parallel Processing
(2016-10-17)], https://goo.gl/mWpMD4[Search Games and `archive.org`
(2016-10-19)]
** *Videos*:
https://www.youtube.com/playlist?list=PLk97mPCd8nvYwbyXe-4FfJlcGbQPwMQKf[Search playlist]
//
. *Security*: [[security]] Alice and Bob, symmetric and asymmetric encryption,
simple ciphers, trapdoor and one-way functions, zero-knowledge proofs,
certificates and certificate authorities, access control, firewalls, hacking,
zero-day exploits, social engineering, famous hacks, personal web security,
denial of service attacks.
** *Activities*: https://goo.gl/Fq4VSV[Capture the Flag (2016-10-24)],
https://goo.gl/oTzI1o[Encryption and ZNP (2016-10-26)]
** *Videos*:
https://www.youtube.com/playlist?list=PLk97mPCd8nvZL-Zi9r6wxbEvI2J1jF-JK[Security playlist]
//
. *Identity*: [[identity]] cookies, server side tracking, IP addresses v.
identities, anonymity online, online v. human identities.
** *Activities*: https://goo.gl/YZ68jb[Video Review Session (2016-10-31)],
https://goo.gl/U8FPYa[Second Life (2016-11-02)]
** *Videos*:
https://www.youtube.com/playlist?list=PLk97mPCd8nvaBrobQf5IsjobG27Wzdfkc[Identity playlist]
//
. *The Interactive Web*: JavaScript, web applications, asynchronous web
requests, modifying the DOM.
** *Activities*: https://goo.gl/MRV3oZ[JavaScript Part I: CodeCombat and
Codecademy (2016-11-07)], https://goo.gl/MRV3oZ[JavaScript Part II: jQuery and
Bootstrap (2016-11-09)]
** *Videos*:
https://www.youtube.com/playlist?list=PLk97mPCd8nvYD3ZxVZin43SghUCH5DP6u[Interactive
playlist]
//
. *The Mobile and Pervasive Web*: internet architecture problems created by
mobility, limitations of mobile devices, mobile web performance problems and
solutions, MPTCP and multihoming, the IoT, pervasive computing, energy and
physical constraints on tiny devices, IPv6 and network growth, the physical
web.
** *Activities*: https://goo.gl/eb2Wp8[The Mobile Web (2016-11-14)],
https://goo.gl/lcw4cR[Your Mobile Site (2016-11-16)]
** *Videos*:
https://www.youtube.com/playlist?list=PLk97mPCd8nvacSuRzHvZDx7stAf-HtULR[Mobility
playlist]
//
. *Your Brain on the Internet*: attention, concentration, distraction, deadly
accidents, search v. knowledge, controlling our internet usage.
** *Activities*: https://goo.gl/9DfyQK[Driven to Distraction (2016-11-21)]
** *Videos*:
https://www.youtube.com/playlist?list=PLk97mPCd8nvbIDe0ol__bk5jNJLJlSDto[Brain
playlist]
//
. *Internet Content and Economics*: early proposals for early payments via
link counting, Bitcoin as an online currency, DRM and other efforts to prevent
digital copying, ongoing efforts to find and block online content.
** *Activities*: https://goo.gl/Ii0ymk[Project Review Session (2016-11-28)],
https://goo.gl/8DvvEY[Bad Ads and Faux News (2016-11-30)]
** *Videos*:
https://www.youtube.com/playlist?list=PLk97mPCd8nvYG2BzAodJLWZLI991llk83[Content
playlist]
//
. *Lost and Future Visions of the Internet*: Berners-Lee’s original vision for
collaborative content and arguments with Netscape, early internet communities
like the WELL, modern internet communities like 4chan and the drug site,
Lessig’s vision of an internet commons, Proposals for future improvements to
the internet architecture, and will they ever be realized?

=== Objectives

The table below describes how this course meets the learning objectives of
the University at Buffalo
https://www.buffalo.edu/ubcurriculum/seminar.html[UB Seminar program]:

[cols=3,options='header',role='small']
|===

| Outcome
| Activities
| Assessment

| Think critically using multiple modes of inquiry
//
| Online quizzes, group projects, video assignment, final assignment
//
| All assignments

| Analyze disciplinary content
//
| Online quizzes, group projects, video assignment, final assignment
//
| All assignments

| Understand and apply methods of close reading, note-taking, analysis, and
synthesis
//
| Online quizzes, group projects, video assignment, final paper
//
| All assignments, but particularly the video assignments

| Recognize and debate ethical issues and academic integrity footnote:[FWIW,
there is no "debate" about academic integrity...]
//
| Group projects
//
| Multiple weekly projects will touch on ethical issues; academic integrity
will be discussed as a downside of web search.

| Demonstrate proficiency in oral discourse and written communication
//
| Video assignments
//
| Preparation of video assignments

| Develop essential research and study skills such as time management
//
| Online quizzes and module scheduling
// 
| Online quizzes ensure students are proceeding at the appropriate pace.

| Utilize eportfolio footnote:[Why?]
//
| Video assignments
//
| Video lessons will be deposited in eportfolio as well as on YouTube.

| Understand the academic expectations pertaining to studentship at the
University at Buffalo and to higher learning at a research university
//
| Group assignments
//
| Inherent to the structure of the course, preparation for class and for
group assignments.

| Develop a broader perspective for help in making life choices in their
college careers and beyond
//
| Group assignments, final paper
//
| Multiple weekly assignments will touch on societal and ethical issues and
discuss how the internet is changing the broader world.

|===

== Grading

Grading is largely driven by participation:

* *30% video participation*: watching the online videos.
//
* *30% activity participation*: coming to class and completing activities
with your group.
//
* *30% video contributions*: recording and uploading three short videos (10%
each) with a group drawn from your activity section.
//
* *10% internet participation*: generating or curating online content.

We discuss each of the grading components in more detail below.

=== Video Participation

Watching the videos _before_ coming to class is critical for <<approach,our
approach>> to work.
//
We will monitor and quantify your progress through the video series in a
variety of ways.
//
Attempting to foil them will be considered a violation of academic integrity.

=== Activity Participation

Equally important to success in this course is coming to class and
participating in the activities.
//
We will assign you to a new random group for each activity section, and one
group member will be responsible for submitting the group's work and
recording what group members were present.

Missing one or two classes during the semester is fine--that happens to
anyone.
//
*However, there is no way to make up for a missed activity section.*
//
If you do not attend for any reason, legitimate or not, you will not receive
credit for the activity.
//
As a result, missing class repeatedly will make it hard to pass this class.

There are 26 activities this semester and we will grade participation out of
22--meaning that you have 4 excused absences.
//
These can be used for any reason: family obligations, leisure travel,
hangovers, alarm configuration mistakes, confusions about what day of the
week it is, not finding your partners, not making it back to check in with
your teaching assistant, etc.
//
That said, we would suggest that you reserve your four excused absences for
interesting uses (like leisure travel) as opposed to for stupid uses (alarm
configuration mistakes).
//
The choice is up to you, but don't contact us after you miss class asking if
you can make up the activity.
//
Regardless of why you missed class, the answer is no footnote:[If you think
that you will legitimately miss more than four classes this term, please come
talk to us. Although... should you be in school at all?].

In addition, if you do not check out with a teaching assistant _during class_
you will also not receive credit for the activity.
//
So please don't forget this step.
//
Luckily, we have enough undergraduate teaching assistants so that there is one
for around four groups, so you should be able to find one at checkout time.

[[videos]]
=== Video Contributions

One of the best ways to learn new material is to explain it to others.
//
We're providing you a way to do that--but to hundreds or thousands of
students in coming years.

During the semester you will need to record three short videos for inclusion
in the link:/[`internet-class.org`] video library.
//
You can work with another student or alone on these assignments, but if
working in a group of two both students need to be involved in several minutes
of the video to receive full credit.
//
Note that both students in a group of two must be both be in CSE 199
footnote:[Duh...?], although they don't have to be in the same section.

==== Grading

Video submissions will be graded on the following criteria:

. *Length* (10%): is the video around five minutes in length?
//
Course concepts have been subdivided appropriately so that they can be
explained in that length of time.
//
If your video is too short, you probably aren't saying enough.
//
If it's too long, you're probably saying too much.
//
. *Participation* (10%): if done in groups of two, does the video involve
both listed participants?
//
Students working alone get this credit for free, so there's a bit of tradeoff
there when determining whether to work with a partner.
//
. *Clarity and Accuracy* (20%): does the video clearly explain the concept?
//
Does the video accurate explain the concept? Do the video authors demonstrate
their depth of knowledge of the material?
//
. *Originality* (20%): does the video explore the idea in a new way and not
one derivative of existing video explanations?
//
. *Excitement* (20%): does the video engage the viewer and make them want to
learn the material?
//
. *Production* (20%): is the video reasonably easy on the eyes and ears?
We're not looking for Hollywood-level production values, but we should be
able to hear and watch the videos without distress.

==== Filming

You are welcome to film your videos in any way you like.
//
We aren't looking for high production values, so your smartphone will probably
work fine.
//
However, UB does have video production studios in the new
http://library.buffalo.edu/silverman/[Silverman Library] on the third floor of
Capen Hall.
//
You can reserve these rooms using
http://libweb1.lib.buffalo.edu/openroom/[this online form].

==== Due Dates

The three video assignments are space out evenly throughout the semester, but
they differ slightly in their requirements.

. *Friday, 9/30/2016*: record an alternate explanation for one of the videos
from Weeks 2&ndash;5. These weeks cover <<connectivity, connectivity (Week
2)>>, <<protocols, protocols (Week 3)>>, <<routing, routing (Week 4)>>, and
<<transport,transport (Week 5)>> footnote:[The Week 1 videos are a bit too
general...].

. *Friday, 11/4/2016*: record an alternate explanation for one of the videos
from Weeks 6&ndash;10. These weeks cover <<naming, naming (Week 6)>>;
<<queries,web queries, documents, and markup (Week 7)>>; <<search, search
(Week 8)>>; <<security,security and authority (Week 9)>>; and
<<identity,identity and privacy (Week 10)>>. *Note that you cannot record the
following videos:*
.. Any of the introductions: "Introduction to internet naming", "Introduction
to web protocols, queries, and documents", "Introduction to search", "Overview
of a single search", etc.
.. Any of the tool videos: "Why you should learn to use the command line",
"You should vote", "What are the Chrome developer tools?", "What should you
not search for?", "How to search the web", etc.

. *Friday, 12/9/2016*: record an explanation for a new lesson related to the
course content not already covered.
//
Your topic can fit in to any of the material covered over the 15 weeks of the
course.
//
You might want to try covering something in more depth than we have already
covered--for example, explain a bit more about how fiber optic cable is made,
or how transatlantic cables are laid.
//
Or you can bring in new material not already covered but relevant.
//
If you are concerned whether your topic is appropriate, please consult with a
member of the course staff *before you start*.

=== Internet Participation

As a final assignment we will ask you to participate in the internet.
//
That can take a variety of forms: creating a personal website or blog,
maintaining a https://www.wikipedia.org/[Wikipedia] page, contributing to a
open source software project perhaps on https://www.github.com[GitHub], etc.
//
We are open to many different ideas here, but just to note: normal social
networking activities _will not_ earn you credit for this activity.
//
You are free and encouraged to submit the personal website that you have been
working on this semester, assuming it meets the guidelines below.

The due date for this assignment will be *Friday 12/16/2016 at 11:59PM EDT.*
//
We will distribute a Google Form for you to to submit your URL and project
description.
//
*Note that you cannot work with a partner on this assignment.*

Final project submissions will be graded on the following criteria:

. Does the URL work? (2 points)
//
. Does the submission meet the basic guidelines? (2 points)
//
.. It's not a Facebook page, LinkedIn profile, Instagram feed, etc.
//
. Is the submission informative, usable, and attractive? (2 points)
//
. Is the submission mobile responsive? (2 points)
//
. Overall rate the submission:
//
.. The minimum: 0 points
.. OK: 1 point
.. Great: 2 points

=== Grade Mapping

Scores from all four CSE 199 sections will be combined and, if needed,
renormalized for the purposes of grading.
//
Your score in the course will be converted to a letter grade as follows:

[cols=3,options='header']
|===

| Letter Grade
| Max
| Min

| A
| 100
| 94

| A-
| 93
| 90

| B+
| 89
| 87

| B
| 86
| 84

| B-
| 83
| 80

| C+
| 79
| 77

| C
| 76
| 74

| C-
| 73
| 70

| D
| 69
| 60

| F
| 59
| 0

|===

=== Incomplete Grades

Please refer to the
http://undergrad-catalog.buffalo.edu/policies/grading/explanation.shtml#incomplete[undergraduate]
incomplete policy. Of particular importance is this language:

[quote]
Students may only be given an *I* grade if they have a passing average in
coursework that has been completed and have well-defined parameters to
complete the course requirements that could result in a grade better than the
default grade. _An *I* grade may not be assigned to a student who
  did not attend the course._

=== Academic Integrity

Please review the http://www.cse.buffalo.edu/shared/policies/academic.php[CSE
Department academic integrity policy] and the UB
http://undergrad-catalog.buffalo.edu/policies/course/integrity.shtml[undergraduate]
academic integrity policy to familiarize yourself with the relevant academic
integrity policies and procedures.
//
*Students that submit plagiarized work will receive a grade of F for the
course.*

=== Disabilities

Please register and coordinate with the Office of Disability Services. Let
the course staff know when accommodations need to be made. We are committed
to helping you learn.

=== Online Resources

This website is the source for all information about the class: the syllabus
(which you are reading) and the video series.

=== Mailing List

All enrolled students will be added to a mailing list which we will use for
course communication.
//
*You are responsible for email messages sent to this list, and to your
`@buffalo.edu` email address.*
//
If you are not enrolled and would like to be added to the list, you can sign
up https://www.internet-class.org/mailman/listinfo/199[here].

== Getting Help

Here's how to--and how not to--get help.

=== Great Ways to Get Help

* *Use the the <<forum,forum>>.*

The online <<forum,forum>> is the place to go to discuss the videos and
activities.
//
This is a great resource because it allows you to get help from anyone at any
time--not just during class or recitation.
//
Please use and contribute to this valuable shared resource.

* *Come to office hours.* We don't hold them for our health and
instructors get bored when there isn't anyone to help!
//
So please don't hesitate to come by, even just to say hi.

=== Bad Ways to Get Help

* *Emailing any staff member using their `@buffalo.edu` email address.*
//
I instruct the staff to ignore these emails.
//
Use the <<forum,forum>> or talk to them during class.


[[sections]]
== Sections

Information specific to each activity section follows.
//
https://blue.cse.buffalo.edu/people/gwa/[Geoffrey Challen] may drop in on any
of these sections at any time.
//
And of course https://blue.cse.buffalo.edu/people/carlnues/[Carl Nuessle] has
been known to show up anywhere at any time as well--so be ready.

=== 199A, 199B, 199C

The three 4PM sections will meet together in Bert's Cafeteria at 4PM on
Mondays and Wednesdays.

. *Instructors*: http://www.cse.buffalo.edu/~hartloff/index.html[Jesse
Hartloff], http://www.cse.buffalo.edu/people/?u=mhertz[Matthew Hertz], and
http://www.cse.buffalo.edu/people/?u=jwinikus[Jennifer Winikus]
//
. *Teaching Assistants*: Junjie Chen, David Dobmeier, Lakshmi Ethiraj, Liam
Gensel Harshita Girase, Richard Hanulewicz, Patrick Jones, Valencia
Kaplinsky, Heeba Kariapper Angus Lam, Lawreen Latif Ian Ngumi Brijesh
Rakholia, Rachel Roberts, Kyle Schoener, Parth Shah Dan Starner Grant Wrazen
and Evan Walley
//
. *Dates and Times*: MW at 4PM in Bert's Cafeteria

==== Calendar

http://goo.gl/RdyBBy[This calendar] shows events for the 4PM sections only.
//
You should also add the <<calendar,CSE 199 global calendar>> to your
calendaring program.
//
You're using a calendaring program, right?

++++
<div class="video-container">
  <div class="show-on-small hide-on-med-and-up">
    <div class="lazy-iframe" data-src="https://calendar.google.com/calendar/embed?mode=AGENDA&amp;showTitle=0&amp;showCalendars=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=jkn2ubsvhjkugbmih1ii8k4q10%40group.calendar.google.com&amp;color=%23853104&amp;ctz=America%2FNew_York"></div>
  </div>
  <div class="hide-on-small-only show-on-med-and-up">
    <div class="lazy-iframe" data-src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showCalendars=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=jkn2ubsvhjkugbmih1ii8k4q10%40group.calendar.google.com&amp;color=%23853104&amp;ctz=America%2FNew_York"></div>
  </div>
</div>
++++

=== 199D

. *Instructor*: http://www.cse.buffalo.edu/people/?u=ahughes6[Andrew Hughes]
footnote:[Whose site is in serious need of an overhaul.]
//
. *Teaching Assistants*: Aishani Bhalla, Mohit Bhatia, Greg Bunyea, Isabelle
Caneda, Wesley Csendom, Michael Drewitt, and occasionally Geoffrey Challen.
//
. *Dates and Times*: MW at 9AM in Alumni 97

==== Calendar

http://goo.gl/HkkXZi[This calendar] shows events for the 9AM section only.
//
You should also add the <<calendar,CSE 199 global calendar>> to your
calendaring program.
//
What do you mean you aren't using a calendaring program?
//
Everyone uses one!

++++
<div class="video-container">
  <div class="show-on-small hide-on-med-and-up">
    <div class="lazy-iframe" data-src="https://calendar.google.com/calendar/embed?mode=AGENDA&amp;showTitle=0&amp;showCalendars=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=uk6or0id7tdictntjsifs6jnvo%40group.calendar.google.com&amp;color=%23853104&amp;ctz=America%2FNew_York"></div>
  </div>
  <div class="hide-on-small-only show-on-med-and-up">
    <div class="lazy-iframe" data-src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showCalendars=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=uk6or0id7tdictntjsifs6jnvo%40group.calendar.google.com&amp;color=%23853104&amp;ctz=America%2FNew_York"></div>
  </div>
</div>
++++

// vim: ts=2:et:ft=asciidoc
